version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    container_name: app_nginx
    depends_on:
      - php # Это правило для nginx чтобы он запускался только после того как запустится `php`
  php: 
    image: php:8.0-fpm
    volumes:
      - ./:/var/www/